import Head from "next/head";
import React, { useEffect, useState } from "react";
import axios from "axios";
import FormDetail from "../../components/organisms/formDetailFlight";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";

function detail() {
  const loggedInUserState = useSelector((state) => state.loggedInUser);
  const { user } = loggedInUserState;
  const router = useRouter();
  const idTicket = router.query.id;
  const [data, setData] = useState([]);

  useEffect(() => {
    getFlightDetail();
  }, [user?.user_id]);

  const getFlightDetail = () => {
    axios
      .get(`https://bypass-ankasa-backend.herokuapp.com/ticket/${idTicket}`)
      .then((res) => {
        const data = res?.data?.data;
        if (data.length === 1) {
          setData(res?.data?.data);
        }
      })
      .catch((err) => {
        console.log(err);
      });
  };

  return (
    <>
      <Head>
        <title>Ankasa - Detail Flight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vector.png" />
      </Head>
      <div className={`d-flex justify-content-center`}>
        <FormDetail data={data} />
      </div>
    </>
  );
}

export default detail;
