import Head from 'next/head';
import React from 'react';
import axios from 'axios';
import FormDetail from '../../components/organisms/formDetailFlight';

export async function getServerSideProps(context) {
   const { id } = context.query;
   const response = await axios({
      method: 'GET',
      url: `https://bypass-ankasa-backend.herokuapp.com/ticket/${id}`,
   });
   return {
      props: {
         data: response?.data?.data,
      },
   };
}

function detail({ data }) {
   return (
      <>
         <Head>
            <title>Ankasa - Detail Flight</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/vector.png" />
         </Head>
         <div className={`d-flex justify-content-center`}>
            <FormDetail data={data} />
         </div>
      </>
   );
}

export default detail;
