import Head from 'next/head';
import React from 'react';
import FormDetail from '../components/organisms/formDetailFlight';

function detail() {
   return (
      <>
         <Head>
            <title>Ankasa - Detail Flight</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/vector.png" />
         </Head>
         <div className={`d-flex justify-content-center`}>
            <FormDetail />
         </div>
      </>
   );
}

export default detail;
