import Head from "next/head";
import React from "react";
import FormNotif from "../components/organisms/formNotif";

//Redux
import { useSelector } from "react-redux";

// Firebase
import { database } from "../firebase";
import { ref, onValue, set } from "firebase/database";

function Notif() {
	const { auth, loggedInUser } = useSelector((state) => state);
	const { user } = loggedInUser;
	console.log(new Date().getTime());
	const [notification, setNotification] = React.useState({});
	const [keys, setKeys] = React.useState([]);

	React.useEffect(() => {
		if (!auth) {
			router.replace("/login");
		}
	}, [auth]);

	React.useEffect(() => {
		const starCountRef = ref(database, `notification/${user?.user_id}`);

		onValue(starCountRef, (snapshot) => {
			const data = snapshot.val();

			if (data && typeof data === "object") {
				setNotification(data);
				setKeys(Object.keys(data).reverse().slice(0, 5));
			}
		});
	}, [user?.user_id]);

	return (
		<>
			<Head>
				<title>Ankasa - Notification</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/vector.png" />
			</Head>
			<div className={`d-flex justify-content-center`}>
				<FormNotif data={{ notification, keys, user: user?.user_id }} />
			</div>
		</>
	);
}

export default Notif;
