import Head from 'next/head';
import React from 'react';
import FormNotif from '../components/organisms/formNotif';

function notif() {
   return (
      <>
         <Head>
            <title>Ankasa - Notification</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/vector.png" />
         </Head>
         <div className={`d-flex justify-content-center`}>
            <FormNotif />
         </div>
      </>
   );
}

export default notif;
